import {
  Activity,
  AppWindow,
  Archive,
  ArrowUp,
  Ban,
  Boxes,
  CircleCheck,
  ClipboardList,
  Clock,
  Cpu,
  FileCheck2,
  Fingerprint,
  Gavel,
  Handshake,
  History,
  KeyRound,
  Link,
  LineChart,
  Lock,
  MessageSquare,
  Package,
  Receipt,
  Route,
  Scale,
  ScrollText,
  Server,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  SquarePen,
  Stethoscope,
  UserCheck,
} from "lucide-react";

export const icons = {
  activity: Activity,
  appWindow: AppWindow,
  archive: Archive,
  arrowUp: ArrowUp,
  ban: Ban,
  boxes: Boxes,
  circleCheck: CircleCheck,
  clipboardList: ClipboardList,
  clock: Clock,
  cpu: Cpu,
  fileCheck: FileCheck2,
  fingerprint: Fingerprint,
  gavel: Gavel,
  handshake: Handshake,
  history: History,
  keyRound: KeyRound,
  lineChart: LineChart,
  link: Link,
  lock: Lock,
  messageSquare: MessageSquare,
  package: Package,
  receipt: Receipt,
  route: Route,
  scale: Scale,
  scrollText: ScrollText,
  server: Server,
  shield: Shield,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  shieldOff: ShieldOff,
  squarePen: SquarePen,
  stethoscope: Stethoscope,
  userCheck: UserCheck,
} as const;

export type IconName = keyof typeof icons;
